### ISSUE TITLE
yAxis value of linechart too big to dispaly fully

### ISSUE THREAD

**Issue by zerkphb** [dc-js/dc.js#942] opened 2015-06-04 07:53 UTC
when the value of y axis is big enough, the left digits of value will be hid.

**Comment by gordonwoodhull** [comment] 2015-06-04 10:05
The layout is not completely automatic. [Increase the left margin](https://github.com/dc-js/dc.js/blob/master/web/docs/api-latest.md#margin-mixin) to compensate.

Duplicate of #713

**Closed by gordonwoodhull** 2015-06-04 10:05 UTC
