### ISSUE TITLE
allow for brush on ordinal bar chart

### ISSUE THREAD

**Issue by jrhite** [dc-js/dc.js#348] opened 2013-10-15 02:49 UTC
Currently an ordinal bar chart forces bars to be clickable and disables the ability to brush filter.

I have several examples of charts I'm working on that are ordinal but would love for them to have a brush filter rather than being clickable.

**Comment by TamatiB** [comment] 2015-09-28 10:02
Has this issue been solved yet? My current solution is to relate the linear scale dimension to categories in legend but this is not ideal.

**Comment by gordonwoodhull** [comment] 2015-09-28 13:11
The issue is still open. Patches welcome!

**Comment by jsmedmar** [comment] 2016-12-03 02:22
Wondering is someone ever worked on this?

**Comment by share-with-me** [comment] 2017-03-09 11:39
Hello all, I am stuck up in a situation where I want to enable brush on ordinal bar chart. Has any progress been made on the same? I am new to dc.js and I am in love with it. Just trying this one feature of brush on ordinal chart. Thanks!

**Comment by gordonwoodhull** [comment] 2017-03-09 15:53
I don't know if anyone has come up with a general solution for this.

The best workaround I can think of is the following:
 1. map your ordinals to integers
 2. use a linear scale
 3. use the (reverse) mapping to drive the function for [chart.xAxis().tickFormat()](https://github.com/d3/d3-3.x-api-reference/blob/master/SVG-Axes.md#tickFormat)

Please let me know if you run into trouble with this - I'd be glad to provide a demo in a fiddle.

**Comment by jsmedmar** [comment] 2017-03-09 21:42
Hey the fiddle would be great, especially for us beginners!

**Comment by gordonwoodhull** [comment] 2017-03-09 23:25
Okay, this is not as simple as I thought, but it's definitely possible.

Here's a fiddle: http://jsfiddle.net/gordonwoodhull/53qg6tg9/8/

We're going to map the ordinal keys of the group into an integer scale. This will be easier if the keys naturally already correspond to numbers, but I'll show the general case here where you have to get the keys from the crossfilter group.

First we grab the keys so we can use the array to change integer indices back into keys:
```js
var keys = sumGroup.all().map(dc.pluck('key')).slice();
```

Then we need to map our data to an integer scale using a fake group:
```js
function id_group(group) {
  return {
    all: function() {
      return group.all().map(function(kv, i) {
        return {key: i, value: kv.value};
      });
    }
  }
}
chart
  .group(index_group(sumGroup));
```

Now set up the linear scale:
```js
chart
  .x(d3.scale.linear().domain([0, keys.length]))
  .brushOn(true)
  .round(Math.floor)
```

Print the ticks using the array of keys:
```js
chart.xAxis().tickFormat(function(i) {
  return keys[i];
});
```

And finally, we're going to need to filter based on the ordinal keys instead of those pesky integers. We'll rewrite the `RangedFilter` so that the dimension will be filtered by a range of strings instead of integers:
```js
chart.filterHandler(function(dimension, filters) {
  return filters.map(function(rangefilt) {
    
    return dc.filters.RangedFilter(keys[rangefilt[0]], keys[rangefilt[1]]);
  });
});
```

This doesn't handle all the extra nonsense that would be needed to center the ticks in the bars. I didn't want to clutter up the example.

None of this nonsense would be necessary if the chart supported this feature, but the feature will require some design (and bring other nonsense into dc.js :wink:) so I hope this workaround is useful in the meantime.

**Comment by gordonwoodhull** [comment] 2017-03-09 23:58
Here are the extra steps needed to get `centerBar` working, in a fiddle:
http://jsfiddle.net/gordonwoodhull/4cmrxb9u/6/

First, dc.js takes the domain very literally, so we adjust it:
```js
chart
  .x(d3.scale.linear().domain([-0.5, keys.length-0.5]))
```

Now tell dc.js to center bars, tell it we **really** want to use rounding with center bars even though we know that causes extra trouble, and set up rounding to compensate for the very literal way that dc.js interprets the x axis and tick positions:

```js
  .centerBar(true).alwaysUseRounding(true)
  .round(function(x) {
    return Math.floor(x) + 0.5;
  })
```

Now we also need to fix the `filterHandler` to round those offset bars *up* to our index integers with `Math.ceil`:
```js
chart.filterHandler(function(dimension, filters) {
  return filters.map(function(rangefilt) {
    var low = keys[Math.ceil(rangefilt[0])], high = keys[Math.ceil(rangefilt[1])] || 'zzz';
    return dc.filters.RangedFilter(low,high);
  });
});
```

Fun stuff!

**Comment by share-with-me** [comment] 2017-03-10 05:43
Hey Gordon, firstly many thanks for the fiddles :D. Yes these would be required for us beginners. By the way, I am in love with the tool and playing almost day and night to generate corelations between entities :D. I ll try my sample with the fiddle codes above. Many thanks once again!

**Comment by crash21** [comment] 2017-04-26 22:58
Hi, can we do the same with line chart?

**Comment by gordonwoodhull** [comment] 2017-04-26 23:33
What happens when you try it?

**Comment by BryanNah** [comment] 2017-09-20 09:26
@gordonwoodhull ...thanks so much for the fiddles...But i still have one problem...The bar chart that is  created doesnt filter other graphs forexample  a bubble chart

**Comment by gordonwoodhull** [comment] 2017-09-25 20:58
Thanks for reporting this @BryanNah - too bad no one mentioned this earlier. I had only thought about the filters that `filterFunction` must return in order to display the brush correctly, not the main purpose of the `filterFunction`: to apply filters!

I've updated the code above. And here is a corrected fork of your fiddle from your question on SO:
https://jsfiddle.net/gordonwoodhull/g34Ldwaz/8/

**Comment by BryanNah** [comment] 2017-09-26 05:39
Thanks so much for ur help @Gordon.. This really works for me. I love using
dc.js and i use it everyday to come up with so many graphs. Am glad to work
with u so that we can make it more popular. I still have more issues to
report which i will do so in the mean time..Otherwise thanks so much the
solution.

**Comment by BryanNah** [comment] 2017-09-28 06:44
Hey @gordonwoodhull . Using the code in the fiddle [https://jsfiddle.net/Nahabwe/5qnbajvk/](url) or any other example which has a bubble chart in it... Is it possible to filter and the values inside each bubble to change. Because all i see is that the bubble can only change the size but not its content inside.
Forexample if i set my dimension as values

**Comment by gordonwoodhull** [comment] 2017-09-28 16:55
Hi @BryanNah, whenever possible, please try to ask unrelated questions either on SO or a new ticket. 

That said, if you're talking about driving the label text with data, sure you can do that. It's just like any other property in that it takes an accessor. Right now it looks like you are using the default [label accessor](http://dc-js.github.io/dc.js/docs/html/dc.baseMixin.html#label__anchor), which uses the key (`total` from your data in this case). You could use whatever function you want here.

**Comment by BryanNah** [comment] 2017-10-20 16:23
Hi @gordonwoodhull , many tanks for the help..i have another question. Is it possible to have a brush on from start to end wen page loads using the fiddle above ...I had done it before using **.filter** function and pass it the domain values but i have tried it now and its breaks the **filterHandler** function because for it works after the page has loaded and filtered something. Is there any way i could change the filterHandler function so that it also dictates the filter  changes when the page loads?.
Thanks so much

**Comment by gordonwoodhull** [comment] 2019-07-02 22:12
I've added [an example which covers this pretty well](http://dc-js.github.io/dc.js/examples/brush-ordinal.html). 

Closing.

**Closed by gordonwoodhull** 2019-07-02 22:12 UTC
Labels: enhancement
