### ISSUE TITLE
"Hybrid" SeriesChart locks y axis min to zero

### ISSUE THREAD

**Issue by aberenyi** [dc-js/dc.js#1805] opened 2021-01-15 11:06 UTC
Hi there,

As you can see [here](https://jsfiddle.net/aberenyi/oambpvgd/) I'm tryig to show a series of data points and regression lines.

The issue is that the y axis starts from 0 - it looks like `elasticY` and `yAxisPadding` are ignored.
It works fine if I only use `ScatterPlot`s as `subChart`s.

I guess I'm looking for a workaround here.

Cheers

p.s. I'm aware of the [regression example](https://dc-js.github.io/dc.js/examples/regression.html), but I'd like to utilise pure dc functions to achieve something similar, i.e. w/o using d3's svg tinkering methods.

**Comment by gordonwoodhull** [comment] 2021-01-15 14:31
This is true of all stacked charts and a duplicate of #667, which provides some workarounds.

It is debatable - sometimes it really needs to be locked to zero on the lower bound and elastic on the upper bound. Probably should be an option, but until then we have workarounds.

**Closed by gordonwoodhull** 2021-01-15 14:31 UTC

**Comment by aberenyi** [comment] 2021-01-15 14:46
Many thanks for the lightning fast response @gordonwoodhull.

I swear I've tried to find similar issues, but I've missed #667 - many thanks for pointing me in the right direction!
