### ISSUE TITLE
Integrating seriesChart and lineChat using compositeChart

### ISSUE THREAD

**Issue by DilipRajkumar** [dc-js/dc.js#1029] opened 2015-10-22 15:28 UTC
I tried to do integrate seriesChart and lineChat using compositeChart, but I am getting following error,  but if I use two line chart it works.  Do you have any work around for that or its not currently supported by DC.js lib.  Any help would be much appreciated.  Thanks in advance.

```javascript
TypeError: _parent is undefined
_g = _parent.append('g');
```

**Comment by alan-unravel** [comment] 2015-11-11 12:50
Series charts are just a wrapper around composite chart so that is happening because you are trying to make a composite of a composite

**Comment by gordonwoodhull** [comment] 2015-11-11 13:11
Thanks @alan-unravel, yes this is a duplicate of #854. 

Seems to be a common request and it would be nice to have a solution.

**Closed by gordonwoodhull** 2015-11-11 13:11 UTC
