### ISSUE TITLE
can't load 'crossfilter'

### ISSUE THREAD

**Issue by lhy1149** [dc-js/dc.js#1293] opened 2017-04-05 01:38 UTC
I installed dc@2.0.2 using 'npm install dc'
then 

import dc from 'dc'

there is an error: can not load 'crossfilter'

i change the following code in dc.js(line:10707)
        define(["d3", "crossfilter"], _dc);
to
        define(["d3", "crossfilter2"], _dc);
and error is gone
so is this a bug?

**Comment by gordonwoodhull** [comment] 2017-04-05 02:19
I presume you're using Webpack. Duplicate of #1214.

It's sort of a bug in the way the community fork of crossfilter is distributed - the package would have to be renamed to match the filename (or vice versa). Currently dc.js is configured to work with AMD, which has a different convention for how modules and filenames should be specified. 

See the linked tickets for more details and workarounds.

**Closed by gordonwoodhull** 2017-04-05 02:19 UTC

**Comment by gordonwoodhull** [comment] 2017-05-24 23:31
As of dc.js 2.0.3 / 2.1.6, we'll break requireJS compatibility in favor of webpack compatibility. 

See #1304 if this creates problems for you.
