### ISSUE TITLE
Switch chart's data property?

### ISSUE THREAD

**Issue by pizza2code** [dc-js/dc.js#1318] opened 2017-07-11 19:57 UTC
Is it possible to switch the data property that a particular histogram uses?  (Tried posting this on StackOverflow but was unable.)

Say I have data points which each have a pressure value measured by a pair of sensors, one from vendor A and one from vendor B.  Can I create a pressure histogram and provide a radio switch which toggles between using `data[i].pressureFromVendorA` and `data[i].pressureFromVendorB`?

I've tried the following code to change an existing chart. But after the first transition, the chart gets stuck and can't be switched back to the other data source:
```javascript
    switchSource(newDimFunc, chart, crossfilterGroup) {
    	const ndx = crossfilterGroup.ndx;
    	const chartDim = ndx.dimension(newDimFunc);
    
    	let theGroup = chartDim.groupAll().reduce( ... ).value();
    
    	theGroup.all = function() {
    			let newObject = [];
    			for (const key in this) {
    				if (this.hasOwnProperty(key) && key != "all") {
    					newObject.push({
    							key: parseInt(key),
    							value: this[key]
    						});
    				}
    			}
    			return newObject;
    		}.bind(theGroup);
    
    	chart.dimension(chartDim).group(theGroup);
    	chart.redraw();
    }
```

**Comment by gordonwoodhull** [comment] 2017-07-11 20:05
Did you try replacing the whole group and doing a redraw? I don't think you should need to do this fake group stuff, unless I'm missing something. Another option is reducing both values in the same group and then switching between two fields within `.value` based on a flag. 

I feel like I'm missing some part of the problem, since your code above is a lot more complicated than I would expect.

**Comment by pizza2code** [comment] 2017-07-11 20:17
I'm confused, does `chart.group(theGroup)` and `chart.redraw()` above not "replac[e] the whole group and do a redraw"?  Or do you mean I need to modify the crossfilter chart group in some way?

**Comment by gordonwoodhull** [comment] 2017-07-11 20:32
It should. I meant, why not create two groups and switch between them, instead of this crazy rebinding of `.all()`? I certainly replace groups all the time but tbh I don't recognize what your code is supposed to do.

**Comment by gordonwoodhull** [comment] 2017-07-14 11:36
I'm going to close this, because I think dc.js handles swapping of group data well in most cases.

If you have a reproducible example where this is not working, please add a link and I'll reopen

**Closed by gordonwoodhull** 2017-07-14 11:36 UTC

**Comment by pizza2code** [comment] 2017-07-14 14:56
Sorry.  Apparently the only part I was missing here was clearing then re-applying any filters.

**Comment by gordonwoodhull** [comment] 2017-07-16 19:37
No problem - glad you got it working!
