### ISSUE TITLE
How to correctly Cleanup/destroy the charts after they are not needed any more?

### ISSUE THREAD

**Issue by KrishnaPG** [dc-js/dc.js#1813] opened 2021-02-09 01:13 UTC
In a single-page application, the charts could be loaded and unload dynamically (through, say, React bindings etc.)

What is the best way to unbind the DOM node and cleanup the charts ( (release the objects / memory) when they are not needed anymore? Any function such as `destroy`, or `cleanup` that need to be called? 

Could not find any such method in the documentation and concerned about the memory usage if we have dozens of charts that are loaded and unloaded on the fly.

For example:
````js
onMount() {
   const chart =  dc.barChart(this.domNode)
}
onUnmount() {
  // do what here to cleanly release the chart objects ??
}
````

**Comment by gordonwoodhull** [comment] 2021-02-09 02:22
This is a duplicate of #1119, which offers some suggestions about how to clean up charts.

The heart of the solution is to deregister the charts when they are no longer needed. There shouldn't be any reference cycles after that, but if you encounter memory leaks, please open a new issue!

**Closed by gordonwoodhull** 2021-02-09 02:22 UTC
