### ISSUE TITLE
Line chart zoom animation bug

### ISSUE THREAD

**Issue by ZlobnyiSerg** [dc-js/dc.js#1091] opened 2016-01-19 22:29 UTC
![dc-zoom-bug](https://cloud.githubusercontent.com/assets/828963/12433978/0741397c-bf15-11e5-89be-87f2edf5c12c.gif)

Zooming with mouse wheel causes very poor visual effects in line chart (the same with bar chart, animation is also broken there). It is much better in 1.7.5

**Comment by gordonwoodhull** [comment] 2016-01-19 22:37
Thanks for the report and the GIF @ZlobnyiSerg. This is a duplicate of #507 and similar problems can be seen on the focus/range chart on the main demo page for dc.js

Basically what is going on is that someone decided, as an optimization, only to include the data which is on the screen, and filter the rest out. But in order for the transition to work right, the entire range of x coordinates that includes both the old range and the new range. In the old code, all the data was always displayed, avoiding the issue.

This is the main regression which is holding back the release of dc.js 2.0.

**Closed by gordonwoodhull** 2016-01-19 22:37 UTC

**Comment by ZlobnyiSerg** [comment] 2016-01-19 22:45
Thank you for explanation (and for your great job). Btw, I was using c3.js charts and they has poor performance even on 365 points in linear chart. So I've tried to migrate to dc.js, and even 1.7.5 is much faster than c3 :)

**Comment by gordonwoodhull** [comment] 2016-01-20 13:49
Huh that's good to know and somewhat surprising. The line and bar chart code in dc.js is some of the oldest and most straightforward. 

It's not too hard to make d3 code efficient, although I suppose there are always ways to slow down code.

I think it is mostly equivalent to what Nick (the original dc.js author) wrote in his book, Data Visualization with D3.js Cookbook, if you or anyone else is interested in the "how and why".

https://www.packtpub.com/web-development/data-visualization-d3js-cookbook
