### ISSUE TITLE
barChart.brushOn(false) prevents clicking on Bars

### ISSUE THREAD

**Issue by awjreynolds** [dc-js/dc.js#614] opened 2014-06-12 09:46 UTC
I was using a linear scale but wanted to remove the brush and allow the user to click the bars using this:

```
.brushOn(false)
.x(d3.scale.linear().domain([0, 24]))
.centerBar (true)
```

It did not allow clicking through.

You can overcome this with:

```
.brushOn(false)
.x(d3.scale.ordinal().domain([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23]))
.xUnits(dc.units.ordinal)
.centerBar (false)
```

Note you have to remove .centerBar (true) to get the bar to center on the value however otherwise it offsets it.

**Comment by gordonwoodhull** [comment] 2019-07-02 22:23
Dupe of #633 

The new [ordinal range/focus example](http://dc-js.github.io/dc.js/examples/brush-ordinal.html) shows how to implement ordinal-style click-to-toggle on a linear scale chart.

I think [the code](https://github.com/dc-js/dc.js/blob/7418eafa8e67bc1c9812a63c56e3874ac3151c9b/web/examples/focus-ordinal-bar.html#L103-L136) should suffice for any place one wants to enable clicking instead of brushing on a bar chart. If not, we could add another example.

**Closed by gordonwoodhull** 2019-07-02 22:23 UTC
Labels: enhancement
