### ISSUE TITLE
dc.baseMixin replaceFilter does not return chart instance

### ISSUE THREAD

**Issue by skidr0w** [dc-js/dc.js#1275] opened 2017-02-08 11:07 UTC
Documentation states, that a call to replaceFilter return the chart instance and therefor can be chained. But the code is missing a return statement.

```javascript
_chart.replaceFilter = function (filter) {
    _filters = _resetFilterHandler(_filters);
    _chart.filter(filter); // missing return here
};
```

**Comment by gordonwoodhull** [comment] 2017-02-08 13:34
Thanks @skidr0w for the report! 

I don't know why I haven't fixed this yet - guess it slipped my mind. It's a duplicate of #1227.

**Closed by gordonwoodhull** 2017-02-08 13:34 UTC
