### ISSUE TITLE
Render dc.barChart in Node.js

### ISSUE THREAD

**Issue by fernandrez** [dc-js/dc.js#1108] opened 2016-02-20 21:37 UTC
Good day I have the following code to try to render a Bar Chart from Node.js using Express Framework and JSDOM:
``
`var express = require('express');
var router = express.Router();
var d3 = require('d3');
var d3request = require('d3-request');
var jsdom = require('jsdom');
global.d3_document = jsdom.jsdom();
var dc = require('dc');

/* GET bar for specific dataframe with given dimensions. */
router.get('/:dftitle/:xdim/:ydim/', function(req, res, next) {
  /* Use d3-request to get the data */ 
  d3request.tsv("http://localhost:3000/data/data.tsv", function(d){
    d.pay = +d.pay;
    d.bal = +d.bal;
    return d;
  }, function(data){
    const containerSelector = 'bar-chart-container';
    var htmlStub = `'<html><head>Hello</head><body><div id="'+containerSelector+'"></div></body></html>';
    `//Render the Chart
    jsdom.env({ features : { QuerySelector : true }, html : htmlStub
      , done : function(errors, window) {
        bcc = window.document.querySelector(containerSelector);
        global.d3_document = window.document;
        var BarChart = dc.barChart(bcc);
        console.log(BarChart);
        res.send(jsdom.serializeDocument(window.document));
      }
    });
grpF: grpF});
  });
});

module.exports = router;`

Its failing exactly at `var BarChart = dc.barChart(bcc);` with the error:
`/usr/local/src/node/s3d3c/node_modules/d3/d3.js:1312
      d3_behavior_zoomWheel = "onwheel" in d3_document ? (d3_behavior_zoomDelta = function() {
                                           ^

TypeError: Cannot use 'in' operator to search for 'onwheel' in undefined
    at Object.d3.behavior.zoom (/usr/local/src/node/s3d3c/node_modules/d3/d3.js:1312:44)
    at Object.dc.coordinateGridMixin (/usr/local/src/node/s3d3c/node_modules/dc/dc.js:2760:29)
    at Object.dc.barChart (/usr/local/src/node/s3d3c/node_modules/dc/dc.js:5277:35)
    at Object.jsdom.env.done (/usr/local/src/node/s3d3c/routes/bars.js:25:27)
    at /usr/local/src/node/s3d3c/node_modules/jsdom/lib/jsdom.js:275:18
    at nextTickCallbackWith0Args (node.js:453:9)
    at process._tickCallback (node.js:382:13)`

Is it possible for this chart to be rendered server side using JSDOM.

**Comment by gordonwoodhull** [comment] 2016-02-20 22:13
Duplicate of https://github.com/dc-js/dc-node/issues/1

**Closed by gordonwoodhull** 2016-02-20 22:13 UTC
