### ISSUE TITLE
Inconsistent behavior when resetting filters for charts in different chart groups

### ISSUE THREAD

**Issue by Kurappu** [dc-js/dc.js#1202] opened 2016-09-02 13:17 UTC
Hello,
I noticed a strange behavior when I reset the filters for all of my charts while some of them belong to another chart group than the default one.
I get different results depending on which chart group I reset first.

[Fiddle](http://jsfiddle.net/ef0no9xh/1/)

If you make a selection in the "B" chart and then click "Reset All b" you'll see that chart "A" is filtered despite no selection. Another click on "Reset All b" completely resets it to its initial state again.
While if a selection is made in the "A" chart and "Reset All b" is clicked it resets as I'd expect.
(And vice versa with the "Reset All a" - button)
I also noticed that if you make a selection in both "A" and "B" you also get weird behavior.

I have not tested this with anything else than range charts (as that's how I found this)

Thanks

**Comment by gordonwoodhull** [comment] 2016-09-03 22:12
Hi @Kurappu, thanks for reporting this. It's an odd one!

I wasn't able to track it down in a quick look. Somehow it looks like each of the focus charts accidentally takes its focus/domain from the other chart, when this happens.

I discovered the problem is happening a little bit earlier - maybe this will help you track it down. I added a redraw all button to this fork of your fiddle:

http://jsfiddle.net/gordonwoodhull/yu1swf2x/1/

If you hit Redraw Alls after making a selection in either range chart, the other chart group will already be filtered.

**Comment by gordonwoodhull** [comment] 2016-09-04 14:21
... which makes sense, because the two chart groups are using the same crossfilter instance, so when the focus chart zooms to a particular range, it filters on that range.

Usually it makes sense to use one crossfilter instance per chart group, because then all the charts on that crossfilter will redraw automatically when others are filtered. I'm not sure what you're creating multiple chart groups for, but if they are supposed to filter independently, maybe make an `ndx = crossfilter(...)` for each one.

I'm closing this issue: if your chart groups share a crossfilter instance, you have to make sure that actions in any group which change the filters are followed by a redraw for all affected chart groups, so instead of 

```js
d3.select('#reseta')
   .on('click', function() {
     dc.filterAll('a');
     dc.redrawAll('a');

     dc.filterAll('b');
     dc.redrawAll('b');
});
```

do

```js
d3.select('#reseta')
   .on('click', function() {
     dc.filterAll('a');
     dc.filterAll('b');

     dc.redrawAll('a');
     dc.redrawAll('b');
});
```

Please comment if there's another bug, or a feature you'd like to see here. I have sometimes wondered if it's always appropriate to filter by the "focus range", but since no one else has complained, I don't think there's an issue for it.

**Closed by gordonwoodhull** 2016-09-04 14:21 UTC
