### ISSUE TITLE
dataTable sorting rows AFTER applying size()

### ISSUE THREAD

**Issue by genuinesmile29** [dc-js/dc.js#1084] opened 2016-01-08 22:03 UTC
I'm using a data table and would like to sort my data by a certain attribute and display the top 10 hits, with a "Show More" button that increments the data table size and redraws it. What I'm finding is that the data table applies the size first, picking 10 random entries and then sorts those. When I increase the data table size, 20 more random entries are added and then sorted. Is there a way to fix this so that size() does not choose arbitrary data elements?

**List of first 10 items:**
![screen shot 2016-01-08 at 5 00 43 pm](https://cloud.githubusercontent.com/assets/1454115/12210645/740baafa-b629-11e5-8191-7ea157f3810a.png)

**List after adding 20 more items:**
![screen shot 2016-01-08 at 5 01 32 pm](https://cloud.githubusercontent.com/assets/1454115/12210652/8241f19c-b629-11e5-8987-b351a5343dd6.png)
...

**Comment by XaserAcheron** [comment] 2016-01-08 22:50
This works fine for me, but I'm explicitly calling `.sortBy` on my dataTables -- are you using this as well?

**Comment by genuinesmile29** [comment] 2016-01-11 16:46
My code is pasted below. It does not seem to matter the order in which the functions are called (whether size is called before or after sortBy). If I do not call size at all, then the sorting problem persists with the default size (25). I am using dc.js-2.0.0-beta.19.

`patientTable.dimension(nameDimension)`
				`.group(function(d) {`
					`return "Selected Patients";`
			`	})`
				`.columns([`
					`{`
			`			label: 'Patient Name',`
			`			format: function(d) { return d.p_name; }`
			`		},`
			`		{`
			`			label: 'FEV Stage',`
			`			format: function(d) { return d.fev_stage; }`
			`		},`
			`		{`
			`			label: 'HRF',`
			`			format: function(d) { return stoplightHtml(d.hrf[0].toLowerCase()); }`
			`		},`
			`		{`
			`			label: 'HRF %',`
			`			format: function(d) { return d.hrf_per; }`
			`		},`
			`		{`
			`			label: 'Risk Factor 1',`
			`			format: function(d) { return stoplightHtml(d.r1); }`
			`		},`
			`		{`
			`			label: 'Risk Factor 2',`
			`			format: function(d) { return stoplightHtml(d.r2); }`
			`		},`
			`		{`
			`			label: 'Risk Factor 3',`
			`			format: function(d) { return stoplightHtml(d.r3); }`
			`		},`
			`		{`
			`			label: 'Risk Factor 4',`
			`			format: function(d) { return stoplightHtml(d.r4); }`
			`		},`
			`	])`
			`	.size(10)`
			`	.sortBy(function(d) {`
			`		return d.hrf_per;`
			`	})`
			`	.order(d3.descending);`

**Comment by genuinesmile29** [comment] 2016-01-11 16:55
I dug into the source code and found the dataTable nestEntries function, which confirms that the size is being applied before sorting. Guess I will have to write a custom version of dataTables that performs the sorting first.

`function nestEntries () {`
 `       var entries;`
  `      if (_order === d3.ascending) {`
   `         entries = _chart.dimension().bottom(_size);`
    `    } else {`
     `       entries = _chart.dimension().top(_size);`
      `  }`

 `       return d3.nest()`
  `          .key(_chart.group())`
   `         .sortKeys(_order)`
    `        .entries(entries.sort(function (a, b) {`
     `           return _order(_sortBy(a), _sortBy(b));`
      `      }));`
    `}`

**Comment by genuinesmile29** [comment] 2016-01-11 17:07
I believe this is only an issue if you are trying to sort your dataTable by something other than the natural ordering of the crossfilter group assigned to the table. In my example I am trying to sort by hrf_per where the natural ordering is by p_name.

**Comment by gordonwoodhull** [comment] 2016-01-11 17:08
Right, it is using the dimension's ordering. Can you use a dimension whose ordering matches the ordering you want?

This is a confusing characteristic of a number of dc.js charts: crossfilter orders the data once and then the chart orders it again.

**Comment by gordonwoodhull** [comment] 2016-01-11 17:08
Since you don't filter from a data table, it shouldn't matter what the key is, right?

**Comment by genuinesmile29** [comment] 2016-01-11 17:20
If I want to add dynamic table sorting in the future, is is possible to change the ordering of a dimension on the fly or will I need a separate dimension for each attribute I want to sort by?

**Comment by gordonwoodhull** [comment] 2016-01-11 17:22
Hmm, yeah, that's annoying. Another thing you could do is set the size infinite and use the pagination features [beginSlice and endSlice](https://github.com/dc-js/dc.js/blob/develop/web/docs/api-latest.md#dc.dataTable+beginSlice) instead, since what you're doing is equivalent to pagination.

**Comment by genuinesmile29** [comment] 2016-01-11 17:24
Can I actually set the size as infinite? Or do I just use a really big number?

**Comment by gordonwoodhull** [comment] 2016-01-11 17:25
Yes, it is standard practice to use the constant `Infinity` as a parameter to crossfilter functions.

**Comment by gordonwoodhull** [comment] 2016-01-11 17:26
and I've confirmed that the data table doesn't use the size for anything else.

**Comment by genuinesmile29** [comment] 2016-01-11 17:36
beginSlice and endSlice are listed in the api as functions of dataTable but in the source code I have (dc.js-2.0.0-beta.19) those are only functions of dataGrid, not dataTable.

**Comment by gordonwoodhull** [comment] 2016-01-11 17:39
I don't understand, they were introduced in beta 20.

**Comment by genuinesmile29** [comment] 2016-01-11 17:48
I was working off the beta 19 release. I pulled the most recent source and it looks like we're in business. I'm still new to git, thanks for your patience!

**Comment by gordonwoodhull** [comment] 2016-01-11 18:52
It's still confusing behavior and maybe not appropriate for a data table, but since there is a solution, I'm going to close this. If you have any suggestions for a cleaner implementation or better documentation, please comment and I'll reopen this.

**Closed by gordonwoodhull** 2016-01-11 18:52 UTC
