### ISSUE TITLE
After setting range in a lineChart with brushOn, cannot select text elsewhere in page.

### ISSUE THREAD

**Issue by TheStoof** [dc-js/dc.js#1174] opened 2016-06-30 20:14 UTC
Hello,

After setting the range in a lineChart with brushOn, I could not select text elsewhere in page. It seems to persist until I refresh the page.

Demo:
http://dc-js.github.io/dc.js/ <-- select Days by Fluctuation and you won't be able to select text anymore.

Regards

**Comment by gordonwoodhull** [comment] 2016-06-30 20:30
Hi @TheStoof, thanks for the report.

I can't reproduce this using the examples (e.g. enabling brushOn on [the line chart example page](http://dc-js.github.io/dc.js/examples/line.html)). Can you create a jsFiddle or otherwise demonstrate the problem so that I can help troubleshoot?

**Comment by gordonwoodhull** [comment] 2016-06-30 20:31
Oh. saw your edit.

**Comment by gordonwoodhull** [comment] 2016-06-30 20:36
I am able to select text in Chrome but not in firefox. This is a duplicate of #1048, which suggests a workaround, if you are not using the zoom feature. 

(Basically we are trying to use two d3 behaviors at once, even though only one is ever active.)

**Closed by gordonwoodhull** 2016-06-30 20:36 UTC
Labels: bug

**Comment by TheStoof** [comment] 2016-06-30 20:38
Hm. I am using the zoom feature, but I can change the workflow to update my DataTables.js via scrolling instead of range selection. 

Thank you for the reply.

**Comment by gordonwoodhull** [comment] 2016-07-01 10:24
Hmm, that's an interesting data point - so you're using the mousewheel zoom, but not panning using a mouse drag?

There may be better workarounds, and obviously this will need to get fixed eventually. The obvious fix would be to make sure the behaviors are removed in last-in, first-out order, if you want to give it a shot.

**Comment by TheStoof** [comment] 2016-07-01 10:31
Using mouse wheel to zoom in + panning works, range selection w/o zoom works, but zoom + panning + range selection prevents text from being selected on the page afterwards in FireFox. I used your workaround and changed the workflow to range selection w/o zoom.
