### ISSUE TITLE
Browser crashes completely using multiple selectMenu with ie11

### ISSUE THREAD

**Issue by gmacherey** [dc-js/dc.js#1334] opened 2017-09-05 09:34 UTC
Hello all,

I am encountering an issue on all my versions of ie11 (even tried on browserstack to check) with dc.js and selectMenu.

Everytime I try to filter data whith selectMenu, with multiple(true) option, using ie11, the browser crashes completely.

To reproduce easily, just open an ie11 browser, and go to the [dc.js selectMenu example page](https://dc-js.github.io/dc.js/examples/select.html), then try to filter data using the multiple selectMenu (the two on the right). The browser will crash instantly.

Has anyone more info about this ?

Thanks a lot in advance for your help !

**Comment by gordonwoodhull** [comment] 2017-09-05 10:53
Hi @gmachery, thanks for the report.

Sorry but I am unable to reproduce on Windows 10, IE 11.540.15063.0

I also previously put in some special cases for multiple select in IE because it was not behaving according to the standards. So that's one more data point.

I don't know if the automated testing we do on IE11 would trigger this.

I'd first make sure you don't have any extensions which cause this. Maybe test on another machine?

**Comment by gmacherey** [comment] 2017-09-05 12:37
Hi @gordonwoodhull, thanks a lot for your quick reply. 

I tried a few different ie versions on different widows versions. Here are whar I could do so far:

With crashes:
latest on windows 7 (see picture one)
![1-crash](https://user-images.githubusercontent.com/25033413/30061436-a450d112-9247-11e7-9c83-6f7d21a06afe.png)

latest on windows 8 (see picture two)
![2-crash](https://user-images.githubusercontent.com/25033413/30061438-a45308a6-9247-11e7-8285-e14d594119d8.png)

No crashes on the latest on windows 10 (see picture 3)
![3-nocrash](https://user-images.githubusercontent.com/25033413/30061437-a45113d4-9247-11e7-8ddb-5446f17d6f51.png)

Hope that helps a little bit ;) I cannot get any error since the app crashes, so nothing is logged in the console.

Thanks also for this awesome library

**Comment by gordonwoodhull** [comment] 2017-09-05 12:46
I see. Thanks for testing this! I think I have VMs for these end-of-life but still widely used OS.

Can't wait till IE goes away and we can rely on people using Edge!

**Comment by gmacherey** [comment] 2017-09-05 12:47
I fully agree ;)

**Comment by vparpoil** [comment] 2017-09-13 14:04
@gordonwoodhull Here is some input for this issue that I found while investigating : 
It seems that the redrawAll function called [here](https://github.com/dc-js/dc.js/blob/develop/src/base-mixin.js#L794) causes the crash. If you change the call to use `renderAll`, it solves the issue on IE 11 (of course, this has the effect of removing all the transitions when selecting data...)

I investigated a bit more but wasn't able to find a fix. I hope it helps !

**Comment by gordonwoodhull** [comment] 2017-09-13 15:16
Thanks @vparpoil! That's really good to know. I wonder if we are missing the right test cases or if for some reason the issue is not triggered by Jasmine.

Sounds like a possible workaround is to only render and not redraw the `selectMenu` (but allow other charts to redraw as normal). `selectMenu` does not benefit from redraw anyway.

Could anyone try 

```js
menu.redraw = menu.render;
```

and report if it helps?

**Comment by vparpoil** [comment] 2017-09-13 16:05
@gordonwoodhull, thank you for your answer. I added
`_chart.redraw = _chart.render;` to `src/select_menu.js`
It does fix the IE crash, but there is an unwanted effect : the `Select All` option stays selected on IE and Chrome (see print screen)
<img width="324" alt="capture d ecran 2017-09-13 a 17 28 22" src="https://user-images.githubusercontent.com/1492912/30385993-0000b862-98a9-11e7-9b11-4d66526314c2.png">
I actually found a workaround and added a pull request here:
https://github.com/dc-js/dc.js/pull/1338

**Comment by gordonwoodhull** [comment] 2017-10-20 15:40
Fixed in 2.1.9

**Closed by gordonwoodhull** 2017-10-20 15:40 UTC
