### ISSUE TITLE
Responsive charts

### ISSUE THREAD

**Issue by eswestra** [dc-js/dc.js#1127] opened 2016-04-12 18:57 UTC
I read that end 2015 charts were made to be responsive, has that been implemented as of yet. Still not working for me

**Comment by gordonwoodhull** [comment] 2016-04-12 19:04
I hope no one had claimed that the whole library is responsive. This has been implemented for some charts but not others. You can view the test pages here:

http://dc-js.github.io/dc.js/resizing/

This is a duplicate of #544, closing.

**Closed by gordonwoodhull** 2016-04-12 19:04 UTC

**Comment by eswestra** [comment] 2016-04-12 19:16
end of post #544 ruhley shows this update http://ruhley.github.io/dc.js/examples/label-wrap.html
This is basically what i need but when i use this code it doesnt work. Has this been implemented yet?

**Comment by gordonwoodhull** [comment] 2016-04-12 19:30
Ah, so @ruhley has a fork of dc.js where he is adding a lot of cool features, but he's not writing new tests or updating the old ones, so it will take some work to merge his code back into the mainline. 

You should definitely try his version of the library! And volunteers are always welcome to help merge these features back.

**Comment by eswestra** [comment] 2016-04-13 06:38
Where can i find this fork,  when i click his link it redirect to main dcjs

**Comment by ruhley** [comment] 2016-04-13 07:34
My fork is available at https://github.com/ruhley/dc.js. As @gordonwoodhull has said there are no tests and there are definitely still bugs in it. Feel free to use my fork and submit issues on it and I will try to fix it promptly.

**Comment by eswestra** [comment] 2016-04-13 09:08
Thanks a lot, a lot of cool features in there, if i find issues, do i post them here, when i go to https://github.com/ruhley/dc.js. there does not seem to be an issues area

**Comment by ruhley** [comment] 2016-04-13 09:50
It seems github disables issues for forks. I have now enabled them.

**Comment by eswestra** [comment] 2016-04-13 09:54
thanks will post an issue there
