### ISSUE TITLE
filterHandler doesn work in seriesChart

### ISSUE THREAD

**Issue by aruizna** [dc-js/dc.js#1354] opened 2017-11-27 19:50 UTC
Hi, in seriesChart is lost the filterHandler function.
In this chart is where this function is really necesari because, the dimention is not a scalar value. it is an object.
The solution I found is to invoke .filterHandler(_chart.filterHandler()) in the delcaration of each subchart.
line 7927: 
dc.seriesChart ->_chart._preprocessData ->
`                return subChart
                    .dimension(_chart.dimension())
                    .group({all: d3.functor(sub.values)}, sub.key)
                    .keyAccessor(_chart.keyAccessor())
                    .valueAccessor(_chart.valueAccessor())
                    .brushOn(_chart.brushOn())
                    .filterHandler(_chart.filterHandler());
`

**Comment by gordonwoodhull** [comment] 2017-11-27 20:29
Thanks for the report, @aruizna! And thanks for sharing your workaround, which will work in some cases but not others. 

Since the series chart is a specialization of the composite chart, this is a duplicate of #878. 

See #390 for some details on when your workaround will and won't work. It doesn't quite make sense to filter the dimension N times just because N charts are using the same data. So I think the right solution is to share the responsibility of filtering. I've done some initial development in this area but unfortunately it has not yet been released due to time constraints.

**Closed by gordonwoodhull** 2017-11-27 20:29 UTC
Labels: bug, duplicate
