### ISSUE TITLE
I am using dc. lineChart () to draw a broken line map. I put the values of the x-axis in reverse order (from large to small). The broken line map can not be displayed properly?

### ISSUE THREAD

**Issue by adminDCTOP** [dc-js/dc.js#1538] opened 2019-07-29 08:16 UTC
Hello, I'm using dc. lineChart () in dcjs. I want the X-axis values to be arranged in reverse order to show the broken line graph. I reorganized the key and value of group in reverse order, but the broken line graph did not display normally:
 the code is as follows:

```js
booingsProfileChart = dc.lineChart("#dc-sonLineOd-chart")
function id_groupODPointerLine(group) {
     return {
        all: function() {
              return group.all().map(function(kv, i) { 
                    let keys = profile_curr_group.all().map(dc.pluck('key')).slice().reverse(),
                        valus = profile_curr_group.all().map(dc.pluck('value')).slice().reverse()
                    return {key: keys[i], value: valus[i]};  
              });   
       }
     }
   }

booingsProfileChart.width(containerWidth)
               .margins({top: 20, right: 70, bottom: 50, left: 40})
               .height(220)
               .transitionDuration(0)
               .x(d3.scaleLinear().domain([340,0]))
               .xAxisLabel("DayPrior")
               .yAxisLabel(yLableValue)
               .clipPadding(10)
               .ordinalColors(['#132B43','#8AC8F7'])
               .elasticY(true)
               .dimension(profile_dimension)
               .controlsUseVisibility(true)
               .useRightYAxis(true)
               .group(id_groupODPointerLine(profile_curr_group),"currBook")
               .stack(id_groupODPointerLine(profile_currLY_group),"cuLyBook")
               .brushOn(false)
               .controlsUseVisibility(true)
               .renderTitle(true)
               .title(function (p,i) {
                 let typeText = p.key,
                     valueText = p.value,
                     curve_date = ODTitleShow(curve_title,i,"curveDate")
                 return [
                  'Date: ' + curve_date,
                  'Dayprior: ' + typeText,
                  'Sum: ' + valueText
                 ].join('\n');
                })
```

I've reversed the value of group, but the line chart can't be displayed?

**Comment by adminDCTOP** [comment] 2019-07-29 11:33
If there is any help, I will be very grateful!

**Comment by gordonwoodhull** [comment] 2019-07-29 14:06
Hi @adminDCTOP! Please be patient, it's only 10am over here.

I doubt it's the problem, but your fake group is excessively complicated. For every iteration, it is mapping, slicing, and reversing `profile_curr_group` twice (and I guess you probably meant `group` here). You could accomplish the same thing with `group.all().slice().reverse()`.

But that's not the real problem. The real problem is that linear scales work completely differently from ordinal scales in dc.js. Reversing the input order for a chart with a linear scale has essentially no effect because X coordinates are assigned on based on the numeric value, not the order that the data arrives. (Well, the line will get drawn backward, but there's no visible effect.)

Instead, reversing the scale, as you are doing with `d3.scaleLinear().domain([340,0])`, should be enough.

However, there are a couple of issues with drawing charts with descending scales, because dc.js assumes in a couple of places that the beginning of the domain is less than the end of the domain. See #749 and especially #525. This issue is basically a duplicate of those.

I was able to draw a descending line with the following modifications:

```js
    chart.evadeDomainFilter(true)
```

disables the domain filtering in the stack mixin, a decent workaround for #525.

Also, for some reason `elasticY` doesn't work for a descending X scale - I can't think why this is and I didn't see it covered in the previous issues.

In my example I set the Y domain and it works:

```js
    chart.y(d3.scaleLinear().domain([0,100])).elasticY(false)
```

Here's my fiddle: https://jsfiddle.net/gordonwoodhull/gnmoqhck/27/

**Comment by gordonwoodhull** [comment] 2019-07-29 15:31
Okay, I figured out why `evadeDomainFilter` fixes the issue with points of the line being dropped, but fails to fix `elasticY`.

Per #1367, even with `evadeDomainFilter` activated, we still drop any points "outside" the X domain when calculating `elasticY`. So all the points in the line get drawn, but the Y domain is `[0,0]`, so it's a flat line. IOW elasticY is still affected by issue #525 and this issue is a duplicate.

**Closed by gordonwoodhull** 2019-07-29 15:31 UTC

**Comment by adminDCTOP** [comment] 2019-07-30 00:37
All right. Thank you very much for your timely reply. Thank you！

**Comment by adminDCTOP** [comment] 2019-07-30 00:43
Okay，Thank you very much for your timely reply！
