### ISSUE TITLE
textFilterWidget : filter is not applied in groups 

### ISSUE THREAD

**Issue by csavelief** [dc-js/dc.js#1812] opened 2021-02-08 20:52 UTC
When a `textFilterWidget` is used inside a `chartGroup`, the charts belonging to this group are not properly filtered.

I believe the problem lies in this piece of code extracted from the `dc.textFilterWidget` function : 

 ```
_input.on('input', function () {
            _chart.dimension().filterFunction(_filterFunctionFactory(this.value));
            dc.events.trigger(function () {
                dc.redrawAll();
            }, dc.constants.EVENT_DELAY);
        });
```

It seems to me that `dc.redrawAll(chartGroup)` should be called instead of `dc.redrawAll()`.

**Comment by gordonwoodhull** [comment] 2021-02-08 21:15
Duplicate of #1498; please check that you are using 4.2.1 or higher.

**Closed by gordonwoodhull** 2021-02-08 21:15 UTC
