### ISSUE TITLE
Looks like a bug in stackchart

### ISSUE THREAD

**Issue by wheercool** [dc-js/dc.js#1021] opened 2015-10-06 11:26 UTC
I use a bunch of crossfilter. My barChart displays current crossfilter data. When I switch current crossfilter the total amount of groups changes. But barChart caches the data points inside `_groupStack` and displays mix of old and new groups.
I found the solution -  I need to call `_groupStack.clear()` to clear old groups.

The only possible way to do this using public methods `stack()`:
```javascript
_chart.stack = function (group, p2, retriever) {
        if(!arguments.length)
            _groupStack.clear();
    
        
        if (typeof p2 === 'string')
            _chart._setGroupName(group, p2, retriever);
        else if (typeof p2 === 'function')
            retriever = p2;

        _groupStack.setDefaultAccessor(_chart.valueAccessor());
        _groupStack.addGroup(group, retriever);

        _chart.expireCache();

        return _chart;
    };
```
But when I call `.stack()` without parameters `group` is undefined and I have an error.
Was `return` statement missed there?
```javascript
_chart.stack = function (group, p2, retriever) {
        if(!arguments.length) {
            _groupStack.clear();
            return;
        }
        ...
    };
```
Another way to fix this problem add  `_groupStack.clear()` inside `calculateDataPointMatrix` method:
```javascript
function calculateDataPointMatrix(data, groupIndex) {
        _groupStack.clear();
        for (var dataIndex = 0; dataIndex < data.length; ++dataIndex) {
            var d = data[dataIndex];
            var key = getKeyFromData(groupIndex, d);
            var value = getValueFromData(groupIndex, d);

            _groupStack.setDataPoint(groupIndex, dataIndex, {data: d, x: key, y: value, layer: groupIndex});
        }
    }.
```

**Comment by gordonwoodhull** [comment] 2015-10-06 13:54
Hi @wheercool, thanks for the report. The 1.7 branch is unsupported and 2.0 is API stable and very close to release. (It's only still in beta because of a couple regressions that need to be fixed.)

This issue is already fixed in the betas:

https://github.com/dc-js/dc.js/blob/master/src/stack-mixin.js#L79-111

How it works is you call `.group()` for the first stack, which resets the stacks. Then call `.stack()` for the rest of them.

Please let me know if this works for you.

**Closed by gordonwoodhull** 2015-10-06 13:54 UTC
Labels: bug, wontfix

**Comment by wheercool** [comment] 2015-10-06 19:40
It works great, thanks!
