### ISSUE TITLE
Proposal - update folder layout

### ISSUE THREAD

**Issue by kum-deepak** [dc-js/dc.js#1565] opened 2019-08-30 13:04 UTC
The proposed changes and their rationale:

- rename `web` to `docs` - this will allow easier management of github pages, by changing the project settings in github. A separate branch and additional steps will no longer be needed.

- create a `dist` folder - this would allow us to create multiple sub folders, `es6` with rolled up file, `esm6` with each module in a file of its own, `css` with css files etc. Further this makes IDEs to clearly identify generated files against source files, making job of refactoring easier.

- creae an `.npmignore` file - this way contents of the npm package can be limited to only files that are needed by users. It will trim down the package size significantly.

**Comment by gordonwoodhull** [comment] 2019-08-30 14:00
We looked into the new github folders. The problem is now you need to check in all of the html artifacts of documentation, which are numerous. Currently we only check those into gh-pages, so it's not so messy. I'm open to discussion on this.

I completely agree on the other two points. I feel bad that the npm distro has been so huge for so long.

**Comment by gordonwoodhull** [comment] 2019-08-30 14:10
Personally I would rather not check in any artifacts at all.

**Comment by kum-deepak** [comment] 2019-09-03 12:05
Makes sense. Will work on only 2nd and 3rd points.

**Comment by kum-deepak** [comment] 2019-09-09 21:16
I have pushed some commits, currently in charts branch:

- https://github.com/dc-js/dc.js/pull/1561/commits/f0404e66437888432c55a6155d17ff78cd316c3b - dropped browserify task
- https://github.com/dc-js/dc.js/pull/1561/commits/4eb998f4f1bfe7791d1e7ee6233c9a94bf3502cc - generated js files now go to dist/es6 and css files go to dist/style folders
- https://github.com/dc-js/dc.js/pull/1561/commits/2d20b19a1c96d43dc4d81c1fb7d8d69f065e210e - first cut of npmignore. First all files are excluded then selectively included. Please check list of files included.
- https://github.com/dc-js/dc.js/pull/1561/commits/636f2046a182859dcec54c13fbc2f9c97a3cfb1f - updated paths as per new folder structure in package.json

**Comment by kum-deepak** [comment] 2019-09-09 21:17
Question: is watch:reload grunt task used?

**Comment by gordonwoodhull** [comment] 2019-12-02 17:48
Fixed by #1627 - we are keeping the old URLs but moving the sources so that `web/` and `dist/` are 100% generated.

**Closed by gordonwoodhull** 2019-12-02 17:48 UTC
Labels: ES6
