### ISSUE TITLE
dc.js is not compatible with latest d3.js(v4).

### ISSUE THREAD

**Issue by nitinmunjani** [dc-js/dc.js#1183] opened 2016-07-20 13:18 UTC
Hello

Can someone please provide me dc.js compatible with latest version of d3.js(v4.1.1).

I am using dc charts in salesforce lightning but salesforce has recently updated locker service for security reason and due to that only latest version of d3.js(v4.1.1)  is working for me. But my dc chart got stopped working as it is referring older d3.js.

Regards
Nitin Munjani

**Comment by gordonwoodhull** [comment] 2016-07-20 13:20
Duplicate of #1173

**Closed by gordonwoodhull** 2016-07-20 13:20 UTC
