### ISSUE TITLE
support for d3 v4

### ISSUE THREAD

**Issue by deely3** [dc-js/dc.js#1331] opened 2017-08-18 12:55 UTC
Hi, I noticed dc.js only works with the pre-v4 version of d3... just curious if there are plans to update?

**Comment by gordonwoodhull** [comment] 2017-08-18 13:00
Duplicate of #1173. 

Summary: I've looked at it and assessed the difficulty. It is not easy as pretty much every feature of d3 has changed. If I somehow find a couple of solid weeks I can dedicate to this I will do it. Others can help by porting individual charts and seeing how bad the work is.

**Closed by gordonwoodhull** 2017-08-18 13:00 UTC

**Comment by deely3** [comment] 2017-08-18 13:33
sorry I didn't see the previous issue - thanks for your response!
