### ISSUE TITLE
add series chart filter

### ISSUE THREAD

**Issue by Amy1989** [dc-js/dc.js#885] opened 2015-03-18 07:17 UTC
Hi,

series chart does not add filter built into it? Adding need to receive it? I would like to ask how to add a filter in series chart, thank you very much

**Comment by gordonwoodhull** [comment] 2015-03-20 18:25
Thanks @Amy1989. I'm going to mark this a duplicate of #878, which links to a search for all the other related issues.  Please try the branch referenced there and see if it works for you.

**Closed by gordonwoodhull** 2015-03-20 18:25 UTC
Labels: duplicate
