### ISSUE TITLE
A range chart can only be used to filter a single companion chart

### ISSUE THREAD

**Issue by eliaslevy** [dc-js/dc.js#958] opened 2015-07-12 01:02 UTC
If you pass the same chart to multiple calls to `rangeChart` in different charts, only a single one of them will be updated when the brush is used in the range chart.

#275 is exactly this issue, but it was closed with a workaround.  The work around is not a proper solution to the issue.  The library should support focusing multiple charts from a single range chart.

**Comment by gordonwoodhull** [comment] 2015-07-12 01:17
Yes, it would be nice to add. I have a decent, general solution here:

http://stackoverflow.com/a/27725811/676195

which could be added directly to the library without too much trouble. (It would need a couple tests, if you care to submit a pull request, hint.) The answer also links to an example, and there is also a simple, slightly less safe answer on the question which should also work in most cases.

**Comment by gordonwoodhull** [comment] 2015-08-16 00:42
This is a duplicate of #820, closing.

**Closed by gordonwoodhull** 2015-08-16 00:42 UTC
Labels: enhancement
